server.port=8080

spring.application.name=email-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${EMAIL_DATABASE_HOST:email-db}:5432/${EMAIL_DATABASE_NAME:email_db}
spring.datasource.username=${EMAIL_DATABASE_USERNAME}
spring.datasource.password=${EMAIL_DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=${MAILTRAP_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAILTRAP_PORT:2525}
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never


app.email.remetente-padrao=${EMAIL_REMETENTE_PADRAO:no-reply@iefc.org.br}
app.email.max-tentativas=${EMAIL_MAX_TENTATIVAS:5}

broker.exchange.name=email.fanout.exchange
broker.queue.name=email.queue

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
