spring.application.name=iefc-backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${IEFC_DATABASE_HOST:iefc-db}:${IEFC_DATABASE_PORT:5432}/${IEFC_DATABASE_NAME:iefc_db}
spring.datasource.username=${IEFC_DATABASE_USERNAME}
spring.datasource.password=${IEFC_DATABASE_PASSWORD}
spring.sql.init.mode=ALWAYS
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#caminho chave publica e privada jwt
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.relatorio.email.destinatario=${RELATORIO_EMAIL_DESTINATARIO:admin@iefc.org.br}

app.email-service.base-url=${EMAIL_SERVICE_BASE_URL:http://email-service:8080}
app.email-service.api-key=${EMAIL_SERVICE_API_KEY:}
app.email-service.remetente=${EMAIL_SERVICE_REMETENTE:no-reply@iefc.org.br}
app.email-service.admin-destinatario=${ADMIN_NOTIFICACAO_EMAIL:admin@iefc.org.br}

app.admin.email=${APP_ADMIN_EMAIL:}
app.admin.senha=${APP_ADMIN_SENHA:}

app.usuario-padrao.email=${APP_USUARIO_PADRAO_EMAIL:}
app.usuario-padrao.senha=${APP_USUARIO_PADRAO_SENHA:}


app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:3000}