/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        navy: 'var(--navy)',
        'navy-hover': 'var(--navy-hover)',
        'teal-accessible': 'var(--teal-accessible)',
        teal: 'var(--teal)',
        amber: 'var(--amber)',
        'amber-light': 'var(--amber-light)',
        'blue-gray': 'var(--blue-gray)',
        mint: 'var(--mint)',
        peach: 'var(--peach)',
        'teal-pale': 'var(--teal-pale)',
        'green-pale': 'var(--green-pale)',
        cream: 'var(--cream)',

        ink: 'var(--ink)',
        'ink-soft': 'var(--ink-soft)',
        'ink-strong': 'var(--ink-strong)',
        'ink-caption': 'var(--ink-caption)',

        border: 'var(--border)',
        'border-warm': 'var(--border-warm)',
        'border-hairline': 'var(--border-hairline)',
        'surface-input': 'var(--surface-input)',
        'input-border': 'var(--input-border)',

        danger: 'var(--danger)',

        'on-dark': 'var(--on-dark)',
        'on-dark-muted': 'var(--on-dark-muted)',
        'on-dark-accent': 'var(--on-dark-accent)',

        'color-text': 'var(--color-text)',
        'color-text-soft': 'var(--color-text-soft)',
        'color-heading': 'var(--color-heading)',
        'color-caption': 'var(--color-caption)',
        'color-link': 'var(--color-link)',
        'color-link-hover': 'var(--color-link-hover)',
        'surface-page': 'var(--surface-page)',
        'surface-card': 'var(--surface-card)',
        'surface-muted': 'var(--surface-muted)',
        'surface-dark': 'var(--surface-dark)',
        'surface-accent': 'var(--surface-accent)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
      },
      fontFamily: {
        display: ['Ubuntu', 'Segoe UI', 'sans-serif'],
        body: ['Open Sans', '-apple-system', 'sans-serif'],
        label: ['Space Grotesk', 'Open Sans', 'sans-serif'],
      },
      fontSize: {
        hero: 'var(--text-hero)',
        h1: 'var(--text-h1)',
        h2: 'var(--text-h2)',
        h3: 'var(--text-h3)',
        lead: 'var(--text-lead)',
        body: 'var(--text-body)',
        'body-lg': 'var(--text-body-lg)',
        small: 'var(--text-small)',
        caption: 'var(--text-caption)',
        label: 'var(--text-label)',
        stat: 'var(--text-stat)',
      },
      lineHeight: {
        tight2: 'var(--lh-tight)',
        heading: 'var(--lh-heading)',
        body2: 'var(--lh-body)',
        snug2: 'var(--lh-snug)',
      },
      letterSpacing: {
        heroLs: 'var(--ls-hero)',
        bodyLs: 'var(--ls-body)',
        labelLs: 'var(--ls-label)',
        labelTight: 'var(--ls-label-tight)',
        eyebrow: 'var(--ls-eyebrow)',
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        section: 'var(--section-pad)',
        page: 'var(--page-margin)',
        'page-mobile': 'var(--page-margin-mobile)',
      },
      maxWidth: {
        content: 'var(--content-max)',
        measure: 'var(--measure)',
      },
      borderRadius: {
        sm2: 'var(--radius-sm)',
        md2: 'var(--radius-md)',
        lg2: 'var(--radius-lg)',
        xl2: 'var(--radius-xl)',
        pill: 'var(--radius-pill)',
        full2: 'var(--radius-full)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        modal: 'var(--shadow-modal)',
        lift: 'var(--shadow-lift)',
      },
      transitionTimingFunction: {
        iefc: 'var(--ease)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        DEFAULT: 'var(--dur)',
      },
    },
  },
  plugins: [],
}
