spring.application.name=fluxy-backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${FLUXY_DATABASE_URL}
spring.datasource.username=${FLUXY_DATABASE_USERNAME}
spring.datasource.password=${FLUXY_DATABASE_PASSWORD}
spring.sql.init.mode=ALWAYS
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${APP_PORT:8080}

#caminho chave publica e privada jwt
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

